Identity(uri='/identities/IDsPJoZjQY3zCteggMYwtCdg', 
application='APiwqrQ7wxQQ6AgJtKz8ibC7', 
created_at='2020-01-24T23:00:30.81Z', 
entity=OrderedDict([('amex_mid', None), 
('annual_card_volume', 12000000), 
('business_address', Object({'city': 'San Mateo', 
'country': 'USA', 
'line1': '741 Douglass St', 
'line2': 'Apartment 8', 
'postal_code': '94114', 
'region': 'CA'})), 
('business_name', 'Namey'), 
('business_phone', '+1 (408) 756-4497'), 
('business_tax_id_provided', True), 
('business_type', 'INDIVIDUAL_SOLE_PROPRIETORSHIP'), 
('default_statement_descriptor', 'Lees Sandwiches'), 
('discover_mid', None), 
('dob', Object({'day': 27, 'month': 6, 'year': 1978})), 
('doing_business_as', 'Lees Sandwiches'), 
('email', 'user@example.org'), 
('first_name', 'dwayne'), 
('has_accepted_credit_cards_previously', True), 
('incorporation_date', Object({'day': 27, 'month': 6, 'year': 1978})), 
('last_name', 'Sunkhronos'), 
('max_transaction_amount', 12000000), 
('mcc', '0742'), 
('ownership_type', 'PRIVATE'), 
('personal_address', Object({'city': 'San Mateo', 'country': 'USA', 'line1': '741 Douglass St', 'line2': 'Apartment 7', 'postal_code': '94114', 'region': 'CA'})), 
('phone', '1234567890'), 
('principal_percentage_ownership', 50), 
('short_business_name', None), 
('tax_id_provided', True), 
('title', 'CEO'), 
('url', 'www.LeesSandwiches.com')]), 
id='IDsPJoZjQY3zCteggMYwtCdg', 
tags=OrderedDict([('Studio Rating', '4.7')]), 
updated_at='2020-01-24T23:00:30.81Z', 
associated_identities=<wac.ResourceCollection object at 0x106702b20>, 
authorizations=<wac.ResourceCollection object at 0x10673a610>, 
disputes=<wac.ResourceCollection object at 0x10673a820>, 
merchants=<wac.ResourceCollection object at 0x10673a730>, 
payment_instruments=<wac.ResourceCollection object at 0x10673a7c0>, 
settlements=<wac.ResourceCollection object at 0x10673a8e0>, 
transfers=<wac.ResourceCollection object at 0x10673a9a0>, 
verifications=<wac.ResourceCollection object at 0x10673aa60>)
